# Generated by Django 3.0.8 on 2020-11-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email_name', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='newitem',
            name='item_label',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='newlabel',
            name='label_name',
            field=models.CharField(max_length=64),
        ),
    ]
