# Generated by Django 3.0.8 on 2020-11-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_auto_20201113_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='newitem',
            name='item_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
