# Generated by Django 3.0.8 on 2020-11-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_newitem_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userslist',
            name='last_name',
        ),
    ]
