# Generated by Django 3.0.8 on 2020-11-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0005_auto_20201114_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslist',
            name='first_name',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='userslist',
            name='last_name',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='userslist',
            name='pass_code',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
