# Generated by Django 3.0.8 on 2020-11-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0006_auto_20201114_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslist',
            name='first_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='userslist',
            name='last_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='userslist',
            name='pass_code',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
