# Generated by Django 3.0.8 on 2020-11-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0007_auto_20201114_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslist',
            name='email_name',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
