# Generated by Django 3.0.8 on 2020-11-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0008_auto_20201114_0713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userslist',
        ),
    ]
