# Generated by Django 3.0.8 on 2020-11-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0009_delete_userslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlabel',
            name='label_home',
            field=models.CharField(max_length=64, null='None'),
            preserve_default='None',
        ),
        migrations.AlterField(
            model_name='newitem',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Newlabel'),
        ),
    ]
