# Generated by Django 3.0.8 on 2020-11-21 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0010_auto_20201121_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitem',
            name='item_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Newlabel'),
        ),
        migrations.AlterField(
            model_name='newitem',
            name='item_name',
            field=models.CharField(max_length=64),
        ),
    ]
