# Generated by Django 3.0.8 on 2020-11-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0011_auto_20201121_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitem',
            name='item_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='newlabel',
            name='label_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
