# Generated by Django 3.0.8 on 2020-11-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0012_auto_20201121_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='newitem',
            name='item_veg',
            field=models.CharField(choices=[('0', 'Veg'), ('1', 'Non-veg')], max_length=30, null=True),
        ),
    ]
