# Generated by Django 3.0.8 on 2020-11-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0013_newitem_item_veg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitem',
            name='item_veg',
            field=models.CharField(choices=[('Veg', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
    ]
