# Generated by Django 3.0.8 on 2020-11-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0014_auto_20201123_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitem',
            name='item_veg',
            field=models.CharField(choices=[('Yes', 'Veg'), ('No', 'Non-Veg')], max_length=30, null=True),
        ),
    ]
