# Generated by Django 3.0.8 on 2020-11-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0017_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
