# Generated by Django 3.0.8 on 2020-11-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0019_auto_20201123_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitem',
            name='item_type',
            field=models.CharField(choices=[('Veg', 'Yes'), ('Non-Veg', 'No')], max_length=30, null=True),
        ),
    ]
