# Generated by Django 3.0.8 on 2020-11-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0020_auto_20201123_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlabel',
            name='label_home',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
