# Generated by Django 3.0.8 on 2020-11-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0021_auto_20201123_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitem',
            name='item_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=30, null=True),
        ),
    ]
