# Generated by Django 3.0.8 on 2020-11-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0025_newitem_label_womb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newitem',
            old_name='label_womb',
            new_name='item_womb',
        ),
    ]
