# Generated by Django 3.0.8 on 2020-11-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0026_auto_20201123_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitem',
            name='item_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='local.Newlabel'),
        ),
    ]
