# Generated by Django 3.0.8 on 2020-11-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0028_auto_20201124_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitem',
            name='item_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
