# Generated by Django 3.0.8 on 2020-11-25 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('local', '0029_auto_20201124_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neworder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order_label', models.CharField(max_length=64, null=True)),
                ('item_order_name', models.CharField(max_length=64, unique=True)),
                ('item_order_number', models.PositiveIntegerField(null=True)),
                ('item_order_price', models.PositiveIntegerField(null=True)),
                ('item_order_total_price', models.PositiveIntegerField(null=True)),
                ('item_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
